### PR TITLE
strace 5.13 -> strace 5.14

### PR DESCRIPTION
**Pull request by persianpros**
Strace 5.13 won't compile with 5.14 headers:

| ../../strace-5.13/src/fs_x_ioctl.c: In function 'fs_x_ioctl':
| ../../strace-5.13/src/fs_x_ioctl.c:64:14: error: invalid application of 'sizeof' to incomplete type 'struct fsxattr'
|    64 |         case FS_IOC_FSGETXATTR:
|       |              ^~~~~~~~~~~~~~~~~
| ../../strace-5.13/src/fs_x_ioctl.c:71:14: error: invalid application of 'sizeof' to incomplete type 'struct fsxattr'
|    71 |         case FS_IOC_FSSETXATTR:
|       |              ^~~~~~~~~~~~~~~~~
| make[3]: *** [Makefile:5011: libstrace_a-fs_x_ioctl.o] Error 1
| make[3]: *** Waiting for unfinished jobs....

According to https://strace.io/files/5.14/:

* Improvements
  * Implemented decoding of memfd_secret and quotactl_fd syscalls,
    introduced in Linux 5.14.
  * Enhanced prctl syscall decoding.
  * Enhanced decoding of IFLA_* netlink attributes.
  * Enhanced decoding of MDBA_ROUTER_PATTR_* mdb router port netlink attributes.
  * Updated lists of BPF_*, IORING_*, MADV_*, MOUNT_ATTR_*, SCTP_*,
    and UFFD_* constants.
  * Updated lists of ioctl commands from Linux 5.14.

### CODE REVIEW

**Comment by persianpros** [comment]
https://github.com/openembedded/openembedded-core/commit/bca3d163d9ed804b4c734ac8fe4fa96e1d05906d

Maybe nobody check PRs on github.
